apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
values:
  gateways:
    istio-eastwestgateway:
      serviceAnnotations:
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      loadBalancerIP: 10.2.0.100 #available ip from the AKS subnet
