apiVersion: v1
kind: Service
metadata:
  name: istio-eastwestgateway
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.0.25
  ports:
  - port: 80
  selector:
    app: istio-eastwestgateway
